// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	session.proto
	signplace.proto

It has these top-level messages:
	Session
	SignPlace
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	User1Id   uint32  `protobuf:"varint,1,opt,name=user1_id,json=user1Id" json:"user1_id,omitempty"`
	User2Id   uint32  `protobuf:"varint,2,opt,name=user2_id,json=user2Id" json:"user2_id,omitempty"`
	StartTs   uint64  `protobuf:"varint,3,opt,name=start_ts,json=startTs" json:"start_ts,omitempty"`
	EndTs     uint64  `protobuf:"varint,4,opt,name=end_ts,json=endTs" json:"end_ts,omitempty"`
	Latitude  float64 `protobuf:"fixed64,5,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,6,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Session) GetUser1Id() uint32 {
	if m != nil {
		return m.User1Id
	}
	return 0
}

func (m *Session) GetUser2Id() uint32 {
	if m != nil {
		return m.User2Id
	}
	return 0
}

func (m *Session) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *Session) GetEndTs() uint64 {
	if m != nil {
		return m.EndTs
	}
	return 0
}

func (m *Session) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Session) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*Session)(nil), "main.Session")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0xbd, 0xca, 0xc2, 0x30,
	0x14, 0xc6, 0x71, 0xce, 0xfb, 0xf6, 0xcb, 0x03, 0x5d, 0x02, 0x42, 0x15, 0x87, 0xe2, 0xd4, 0x49,
	0xb0, 0x5e, 0x85, 0x6b, 0xec, 0x5e, 0x22, 0x09, 0x12, 0xa8, 0x89, 0xe4, 0x9c, 0x5e, 0x95, 0x37,
	0x29, 0x4d, 0xd0, 0x8e, 0xff, 0xe7, 0xb7, 0x3c, 0x58, 0x93, 0x21, 0xb2, 0xde, 0x9d, 0x5e, 0xc1,
	0xb3, 0x17, 0xd9, 0x53, 0x59, 0x77, 0x7c, 0x03, 0x96, 0xb7, 0xb4, 0x8b, 0x1d, 0x56, 0x33, 0x99,
	0x70, 0x1e, 0xad, 0x6e, 0xa0, 0x85, 0xae, 0x96, 0x65, 0xec, 0xab, 0xfe, 0x52, 0xbf, 0xd0, 0xdf,
	0x4a, 0x7d, 0x22, 0x62, 0x15, 0x78, 0x64, 0x6a, 0xfe, 0x5b, 0xe8, 0x32, 0x59, 0xc6, 0x1e, 0x48,
	0x6c, 0xb1, 0x30, 0x4e, 0x2f, 0x90, 0x45, 0xc8, 0x8d, 0xd3, 0x03, 0x89, 0x3d, 0x56, 0x93, 0x62,
	0xcb, 0xb3, 0x36, 0x4d, 0xde, 0x42, 0x07, 0xf2, 0xd7, 0xe2, 0x80, 0x9b, 0xc9, 0xbb, 0x47, 0xc2,
	0x22, 0xe2, 0x3a, 0xdc, 0x8b, 0x78, 0xfd, 0xf2, 0x09, 0x00, 0x00, 0xff, 0xff, 0x70, 0x28, 0xab,
	0x33, 0xcb, 0x00, 0x00, 0x00,
}
